apiVersion: v2
name: capa-iam-operator
version: 2.0.3-dev
description: "Operator for managing IAM roles for CAPA clusters"
appVersion: 2.0.3-dev
home: "https://github.com/giantswarm/capa-iam-operator"
icon: https://s.giantswarm.io/app-icons/giantswarm/1/dark.svg
annotations:
  config.giantswarm.io/version: 1.x.x
  io.giantswarm.application.team: phoenix
